#!/bin/bash -x

echo "add remotes that point to github repos (that we control)"
$(cd Spigot-API && git remote add sconover git@github.com:sconover/spigot-bukkit.git)
$(cd Spigot-Server && git remote add sconover git@github.com:sconover/spigot-craftbukkit.git)
git remote add sconover git@github.com:sconover/spigot-spigot.git
mkdir ../../mcserverdata
